version: '3.7'

services:
  postgres:
    image: 'postgres:13.0'
    hostname: postgres
    container_name: db.kwk.postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: db.kwk.redis
    restart: unless-stopped
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis/data
volumes:
  postgres:
    name: nest-db
  redis:
    name: nest-redis
